Send all messages to STDERR

diff --git a/bin/eb-env-create b/bin/eb-env-create
--- a/bin/eb-env-create
+++ b/bin/eb-env-create
@@ -22,7 +22,7 @@ usage () {
 
 abort () {
     echo "Error:" "$@" >&2
-    echo "Aborting!"
+    echo "Aborting!" >&2
     exit 1
 }
 
